const User = require("../models/User");

// Get the profile of the currently logged-in user
exports.getProfile = async (req, res) => {
  try {
    const userId = req.session.userId;
    if (!userId) {
      return res.status(401).json({ message: "Not authenticated" });
    }

    const user = await User.findById(userId).select("-passwordHash");
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    res.json(user);
  } catch (err) {
    console.error("Error in getProfile:", err);
    res.status(500).json({ message: "Server error" });
  }
};

// Get a student's public profile by ID (for recruiters viewing applicants)
exports.getStudentProfileById = async (req, res) => {
  try {
    if (!req.session.userId) {
      return res.status(401).json({ message: "Not authenticated" });
    }

    const student = await User.findById(req.params.id).select("-passwordHash");
    if (!student) {
      return res.status(404).json({ message: "Student not found" });
    }
    if (student.role !== "student") {
      return res.status(400).json({ message: "User is not a student" });
    }

    res.json(student);
  } catch (err) {
    console.error("Error in getStudentProfileById:", err);
    res.status(500).json({ message: "Server error" });
  }
};

// Update the profile of the currently logged-in user
// Uses dot-notation $set so we ONLY touch the fields being updated,
// avoiding conflicts with legacy data shapes (e.g. education stored as a string).
exports.updateProfile = async (req, res) => {
  try {
    const userId = req.session.userId;
    if (!userId) {
      return res.status(401).json({ message: "Not authenticated" });
    }

    const setFields = {};

    // Allow updating name
    if (req.body.name) {
      setFields.name = req.body.name;
    }

    // Build dot-notation updates for each studentProfile sub-field
    if (req.body.studentProfile) {
      const sp = req.body.studentProfile;

      // contactInfo
      if (sp.contactInfo) {
        if (sp.contactInfo.phone !== undefined) setFields["studentProfile.contactInfo.phone"] = sp.contactInfo.phone;
        if (sp.contactInfo.location !== undefined) setFields["studentProfile.contactInfo.location"] = sp.contactInfo.location;
      }

      // careerPreferences
      if (sp.careerPreferences) {
        if (sp.careerPreferences.preferredJobType !== undefined) setFields["studentProfile.careerPreferences.preferredJobType"] = sp.careerPreferences.preferredJobType;
        if (sp.careerPreferences.availability !== undefined) setFields["studentProfile.careerPreferences.availability"] = sp.careerPreferences.availability;
        if (sp.careerPreferences.preferredLocations !== undefined) setFields["studentProfile.careerPreferences.preferredLocations"] = sp.careerPreferences.preferredLocations;
      }

      // Array fields — only update if explicitly sent AND is a valid array
      if (Array.isArray(sp.education)) setFields["studentProfile.education"] = sp.education;
      if (Array.isArray(sp.skills)) setFields["studentProfile.skills"] = sp.skills;
      if (Array.isArray(sp.languages)) setFields["studentProfile.languages"] = sp.languages;
      if (Array.isArray(sp.internships)) setFields["studentProfile.internships"] = sp.internships;
      if (Array.isArray(sp.projects)) setFields["studentProfile.projects"] = sp.projects;
      if (Array.isArray(sp.achievements)) setFields["studentProfile.achievements"] = sp.achievements;

      // Simple string fields
      if (sp.profileSummary !== undefined) setFields["studentProfile.profileSummary"] = sp.profileSummary;
      if (sp.github !== undefined) setFields["studentProfile.github"] = sp.github;
      if (sp.linkedin !== undefined) setFields["studentProfile.linkedin"] = sp.linkedin;
    }

    const user = await User.findByIdAndUpdate(
      userId,
      { $set: setFields },
      { new: true }
    ).select("-passwordHash");

    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    res.json({ message: "Profile updated successfully", user });
  } catch (err) {
    console.error("Error in updateProfile:", err);
    res.status(500).json({ message: "Server error: " + err.message });
  }
};

// Handle resume upload
exports.uploadResume = async (req, res) => {
  try {
    const userId = req.session.userId;
    if (!userId) {
      return res.status(401).json({ message: "Not authenticated" });
    }

    if (!req.file) {
      return res.status(400).json({ message: "No file uploaded" });
    }

    // req.file contains filename generated by multer
    // We construct the URL to access the uploaded file statically
    const fileUrl = `/uploads/resumes/${req.file.filename}`;
    const originalName = req.file.originalname;

    // Update the user's resume URL
    const user = await User.findByIdAndUpdate(
      userId,
      { 
        $set: { 
          "studentProfile.resume.url": fileUrl,
          "studentProfile.resume.filename": originalName
        } 
      },
      { new: true }
    ).select("-passwordHash");

    res.json({ 
      message: "Resume uploaded successfully", 
      resumeUrl: fileUrl,
      filename: originalName,
      user
    });
  } catch (err) {
    console.error("Error in uploadResume:", err);
    res.status(500).json({ message: "Server error" });
  }
};

// Handle profile picture upload
exports.uploadProfilePic = async (req, res) => {
  try {
    const userId = req.session.userId;
    if (!userId) {
      return res.status(401).json({ message: "Not authenticated" });
    }

    if (!req.file) {
      return res.status(400).json({ message: "No file uploaded" });
    }

    // req.file contains filename generated by multer
    // We construct the URL to access the uploaded file statically
    const fileUrl = `/uploads/pictures/${req.file.filename}`;

    // Update the user's profilePic URL
    const user = await User.findByIdAndUpdate(
      userId,
      { 
        $set: { 
          "studentProfile.profilePic": fileUrl
        } 
      },
      { new: true }
    ).select("-passwordHash");

    res.json({ 
      message: "Profile picture uploaded successfully", 
      profilePicUrl: fileUrl,
      user
    });
  } catch (err) {
    console.error("Error in uploadProfilePic:", err);
    res.status(500).json({ message: "Server error" });
  }
};
